# Generated by Django 3.1.7 on 2021-05-17 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_auto_20210322_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=150, verbose_name='Articulo')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripcion')),
                ('imagen', models.ImageField(upload_to='articulos', verbose_name='Imagen')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio unitario')),
                ('stock', models.IntegerField(verbose_name='Unidades')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulo', verbose_name='Articulo')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articulos.venta', verbose_name='Venta')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articulos.categoria', verbose_name='Categoria'),
        ),
    ]
